# CS110 C++ Makefile for MapReduce sample
# The only make directive supported by this Makefile is make clean,
# which clears away all of the intermediate and output files generated
# when MapReduce (e.g. the executable mr) is run.

clean:
	@rm -fr files/log/* files/map-output/* files/reduce-input/* files/output/*
