Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_06.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_08.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_12.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_10.txt".
Mapper exit code: 0.
