Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_03.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_09.txt".
Mapper exit code: 1.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_09.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_05.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_01.txt".
Mapper exit code: 0.
