Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_02.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_07.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_01.txt".
Mapper exit code: 1.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_07.txt".
Mapper exit code: 0.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_12.txt".
Mapper exit code: 1.
Processing infile: "/usr/class/cs110/samples/assign7/odyssey-full/odyssey_12.txt".
Mapper exit code: 0.
