Processing input chunk: "/usr/class/cs110/samples/assign7-soln/files/reduce-input/2.grouped".
Reducer exit code: 0.
Processing input chunk: "/usr/class/cs110/samples/assign7-soln/files/reduce-input/3.grouped".
Reducer exit code: 0.
Processing input chunk: "/usr/class/cs110/samples/assign7-soln/files/reduce-input/1.grouped".
Reducer exit code: 1.
Processing input chunk: "/usr/class/cs110/samples/assign7-soln/files/reduce-input/1.grouped".
Reducer exit code: 0.
